### PR TITLE
First attempt for the client

### PR DESCRIPTION
**Pull request by dev-tim**
Here I added the first attempt to the client based on the [React Starter Kit](https://github.com/kriasoft/react-starter-kit/blob/feature/redux/README.md) 🚀 . 

It's quite comprehensive and has a lot of necessary tools to build scalable react app. In case if anyone has questions, please shoot, otherwise I'll merge and start working on the simple app concerned with our needs (according to the mockups suggested by @oliversauter)

### CODE REVIEW

**Comment by oliversauter** [comment]
@grady-lad interesting for you

**Comment by dev-tim** [comment]
Yup, it's a bit too big for review, but still can save us a lot of time.

**Comment by oliversauter** [comment]
Am I assuming right, that what you uploaded as react starter kit is just a standard code base to start off?

> but still can save us a lot of time.

What do you mean by that?

**Comment by dev-tim** [comment]
We can reuse project/tools setup from there.

2016-07-10 1:06 GMT+02:00 Oliver Sauter <notifications@github.com>:

**Comment by dev-tim** [comment]
I'll merge ot to unblock further development.

**Comment by lwm** [comment]
@dev-tim you'll definitely need to sync with @grady-lad !!!

**Pull request merged**
